# Tree-sitter runtime + grammars, fetched and built from source.
#
# Provides:
#   - target `tree-sitter` (the C runtime)
#   - one static lib per grammar (`ts_<lang>`), collected into `diffy_ts_grammars`
#   - a generated source defining diffy::ts_raw_queries() — each grammar's
#     embedded queries/highlights.scm keyed by language name
#
# add_ts_grammar(<lang> <repo> <tag> [SUBDIR <dir>] [QUERY <relpath>])
#   SUBDIR : grammar lives in a subdirectory (e.g. typescript/, tsx/, php/)
#   QUERY  : highlights query path relative to the repo (default queries/highlights.scm)

include(FetchContent)

# The runtime and grammars are C; the top-level project only enables C++.
enable_language(C)

# --- runtime --------------------------------------------------------------
# Populate only (SOURCE_SUBDIR points at a non-existent dir so MakeAvailable
# skips the repo's own CMakeLists); we compile the amalgamation ourselves.
FetchContent_Declare(treesitter
  GIT_REPOSITORY https://github.com/tree-sitter/tree-sitter.git
  GIT_TAG v0.22.6
  GIT_SHALLOW TRUE
  SOURCE_SUBDIR __diffy_skip__)
FetchContent_MakeAvailable(treesitter)

add_library(tree-sitter STATIC ${treesitter_SOURCE_DIR}/lib/src/lib.c)
target_include_directories(tree-sitter
  PUBLIC ${treesitter_SOURCE_DIR}/lib/include
  PRIVATE ${treesitter_SOURCE_DIR}/lib/src)
set_target_properties(tree-sitter PROPERTIES C_STANDARD 11)
# These are large generated/third-party C files; silence their warnings so a
# global -Werror/-WX can't fail the build.
if(MSVC)
  target_compile_options(tree-sitter PRIVATE /W0)
else()
  target_compile_options(tree-sitter PRIVATE -w)
endif()

# Collects all grammar libraries.
add_library(diffy_ts_grammars INTERFACE)
target_link_libraries(diffy_ts_grammars INTERFACE tree-sitter)

set_property(GLOBAL PROPERTY DIFFY_TS_QUERIES "")

function(add_ts_grammar lang repo tag)
  cmake_parse_arguments(G "" "SUBDIR;QUERY" "" ${ARGN})

  FetchContent_Declare(ts_${lang}
    GIT_REPOSITORY ${repo}
    GIT_TAG ${tag}
    GIT_SHALLOW TRUE
    SOURCE_SUBDIR __diffy_skip__)
  FetchContent_MakeAvailable(ts_${lang})
  set(root ${ts_${lang}_SOURCE_DIR})

  if(G_SUBDIR)
    set(gsrc ${root}/${G_SUBDIR}/src)
  else()
    set(gsrc ${root}/src)
  endif()

  set(sources ${gsrc}/parser.c)
  if(EXISTS ${gsrc}/scanner.c)
    list(APPEND sources ${gsrc}/scanner.c)
  elseif(EXISTS ${gsrc}/scanner.cc)
    list(APPEND sources ${gsrc}/scanner.cc)
  endif()

  add_library(ts_${lang} STATIC ${sources})
  # parser.c includes "tree_sitter/parser.h", vendored under the grammar's src.
  target_include_directories(ts_${lang} PRIVATE ${gsrc})
  set_target_properties(ts_${lang} PROPERTIES C_STANDARD 11)
  if(MSVC)
    target_compile_options(ts_${lang} PRIVATE /W0)
  else()
    target_compile_options(ts_${lang} PRIVATE -w)
  endif()
  target_link_libraries(diffy_ts_grammars INTERFACE ts_${lang})

  if(G_QUERY)
    set(qpath ${root}/${G_QUERY})
  else()
    set(qpath ${root}/queries/highlights.scm)
  endif()
  set_property(GLOBAL APPEND PROPERTY DIFFY_TS_QUERIES "${lang}|${qpath}")
endfunction()

# Writes a .cc defining diffy::ts_raw_queries() from every grammar's query file.
function(finalize_ts_queries out_cc)
  get_property(pairs GLOBAL PROPERTY DIFFY_TS_QUERIES)
  set(body "")
  foreach(p ${pairs})
    string(REPLACE "|" ";" kv "${p}")
    list(GET kv 0 lang)
    list(GET kv 1 path)
    if(EXISTS ${path})
      file(READ ${path} q)
      string(APPEND body "    {\"${lang}\", R\"DIFFYQ(\n${q}\n)DIFFYQ\"},\n")
    endif()
  endforeach()
  file(WRITE ${out_cc}
"// Generated by treesitter.cmake — do not edit.\n#include <map>\n#include <string>\nnamespace diffy {\nconst std::map<std::string, std::string>&\nts_raw_queries() {\n  static const std::map<std::string, std::string> m = {\n${body}  };\n  return m;\n}\n}  // namespace diffy\n")
endfunction()

# --- the grammar set ------------------------------------------------------
# Pinned to tags from the tree-sitter 0.21/0.22 era for language-ABI 14
# compatibility with the runtime above. (lang repo tag [SUBDIR ..])
add_ts_grammar(c          https://github.com/tree-sitter/tree-sitter-c.git          v0.21.4)
add_ts_grammar(cpp        https://github.com/tree-sitter/tree-sitter-cpp.git        v0.22.0)
add_ts_grammar(go         https://github.com/tree-sitter/tree-sitter-go.git         v0.21.0)
add_ts_grammar(rust       https://github.com/tree-sitter/tree-sitter-rust.git       v0.21.2)
add_ts_grammar(java       https://github.com/tree-sitter/tree-sitter-java.git       v0.21.0)
add_ts_grammar(python     https://github.com/tree-sitter/tree-sitter-python.git     v0.21.0)
add_ts_grammar(javascript https://github.com/tree-sitter/tree-sitter-javascript.git v0.21.4)
add_ts_grammar(typescript https://github.com/tree-sitter/tree-sitter-typescript.git v0.21.2 SUBDIR typescript)
add_ts_grammar(tsx        https://github.com/tree-sitter/tree-sitter-typescript.git v0.21.2 SUBDIR tsx)
add_ts_grammar(ruby       https://github.com/tree-sitter/tree-sitter-ruby.git       v0.21.0)
add_ts_grammar(bash       https://github.com/tree-sitter/tree-sitter-bash.git       v0.21.0)
add_ts_grammar(c_sharp    https://github.com/tree-sitter/tree-sitter-c-sharp.git    v0.21.3)
add_ts_grammar(html       https://github.com/tree-sitter/tree-sitter-html.git       v0.20.3)
add_ts_grammar(css        https://github.com/tree-sitter/tree-sitter-css.git        v0.21.0)
add_ts_grammar(json       https://github.com/tree-sitter/tree-sitter-json.git       v0.21.0)

finalize_ts_queries(${CMAKE_CURRENT_BINARY_DIR}/ts_queries_generated.cc)
