# Tree-sitter runtime + grammars, vendored as git submodules under subprojects/.
#
# Provides:
#   - target `tree-sitter` (the C runtime)
#   - one static lib per grammar (`ts_<lang>`), collected into `diffy_ts_grammars`
#   - a generated source defining diffy::ts_raw_queries() — each grammar's
#     embedded queries/highlights.scm keyed by language name
#
# add_ts_grammar(<lang> <submodule-dir> [SUBDIR <dir>] [QUERY <relpath>] [LOCAL_QUERY <abs>])
#   <submodule-dir> : directory name under subprojects/ (e.g. tree-sitter-c)
#   SUBDIR : grammar lives in a subdirectory of the repo (e.g. typescript/, tsx/)
#   QUERY  : highlights query path relative to the repo (default queries/highlights.scm)
#   LOCAL_QUERY : an absolute path to a highlights query we ship (grammars w/ none)

# The runtime and grammars are C; the top-level project only enables C++.
enable_language(C)

# Root holding the tree-sitter submodules.
set(DIFFY_TS_ROOT ${CMAKE_SOURCE_DIR}/subprojects)

if(NOT EXISTS ${DIFFY_TS_ROOT}/tree-sitter/lib/src/lib.c)
  message(FATAL_ERROR
    "tree-sitter submodule not found at ${DIFFY_TS_ROOT}/tree-sitter.\n"
    "Initialize submodules first:\n"
    "    git submodule update --init --recursive\n"
    "or configure with -DDIFFY_ENABLE_HIGHLIGHT=OFF to build without highlighting.")
endif()

# --- runtime --------------------------------------------------------------
add_library(tree-sitter STATIC ${DIFFY_TS_ROOT}/tree-sitter/lib/src/lib.c)
target_include_directories(tree-sitter
  PUBLIC ${DIFFY_TS_ROOT}/tree-sitter/lib/include
  PRIVATE ${DIFFY_TS_ROOT}/tree-sitter/lib/src)
set_target_properties(tree-sitter PROPERTIES C_STANDARD 11)
# These are large generated/third-party C files; silence their warnings so a
# global -Werror/-WX can't fail the build.
if(MSVC)
  target_compile_options(tree-sitter PRIVATE /W0)
else()
  target_compile_options(tree-sitter PRIVATE -w)
endif()

# Collects all grammar libraries.
add_library(diffy_ts_grammars INTERFACE)
target_link_libraries(diffy_ts_grammars INTERFACE tree-sitter)

set_property(GLOBAL PROPERTY DIFFY_TS_QUERIES "")

function(add_ts_grammar lang repo_dir)
  cmake_parse_arguments(G "" "SUBDIR;QUERY;LOCAL_QUERY" "" ${ARGN})

  set(root ${DIFFY_TS_ROOT}/${repo_dir})

  if(G_SUBDIR)
    set(gsrc ${root}/${G_SUBDIR}/src)
  else()
    set(gsrc ${root}/src)
  endif()

  if(NOT EXISTS ${gsrc}/parser.c)
    message(FATAL_ERROR
      "tree-sitter grammar '${lang}' missing at ${gsrc}.\n"
      "Run: git submodule update --init --recursive")
  endif()

  set(sources ${gsrc}/parser.c)
  if(EXISTS ${gsrc}/scanner.c)
    list(APPEND sources ${gsrc}/scanner.c)
  elseif(EXISTS ${gsrc}/scanner.cc)
    list(APPEND sources ${gsrc}/scanner.cc)
  endif()

  add_library(ts_${lang} STATIC ${sources})
  # parser.c includes "tree_sitter/parser.h", vendored under the grammar's src.
  target_include_directories(ts_${lang} PRIVATE ${gsrc})
  set_target_properties(ts_${lang} PROPERTIES C_STANDARD 11)
  if(MSVC)
    target_compile_options(ts_${lang} PRIVATE /W0)
  else()
    target_compile_options(ts_${lang} PRIVATE -w)
  endif()
  target_link_libraries(diffy_ts_grammars INTERFACE ts_${lang})

  if(G_LOCAL_QUERY)
    set(qpath ${G_LOCAL_QUERY})
  elseif(G_QUERY)
    set(qpath ${root}/${G_QUERY})
  else()
    set(qpath ${root}/queries/highlights.scm)
  endif()
  set_property(GLOBAL APPEND PROPERTY DIFFY_TS_QUERIES "${lang}|${qpath}")
endfunction()

# Writes a .cc defining diffy::ts_raw_queries() from every grammar's query file.
function(finalize_ts_queries out_cc)
  get_property(pairs GLOBAL PROPERTY DIFFY_TS_QUERIES)
  set(body "")
  foreach(p ${pairs})
    string(REPLACE "|" ";" kv "${p}")
    list(GET kv 0 lang)
    list(GET kv 1 path)
    if(EXISTS ${path})
      file(READ ${path} q)
      string(APPEND body "    {\"${lang}\", R\"DIFFYQ(\n${q}\n)DIFFYQ\"},\n")
    endif()
  endforeach()
  file(WRITE ${out_cc}
"// Generated by treesitter.cmake — do not edit.\n#include <map>\n#include <string>\nnamespace diffy {\nconst std::map<std::string, std::string>&\nts_raw_queries() {\n  static const std::map<std::string, std::string> m = {\n${body}  };\n  return m;\n}\n}  // namespace diffy\n")
endfunction()

# --- the grammar set ------------------------------------------------------
# Each <dir> is a submodule under subprojects/, pinned to a tag from the
# tree-sitter 0.21/0.22 era for language-ABI 14 compatibility with the runtime.
add_ts_grammar(c          tree-sitter-c)
add_ts_grammar(cpp        tree-sitter-cpp)
add_ts_grammar(go         tree-sitter-go)
add_ts_grammar(rust       tree-sitter-rust)
add_ts_grammar(java       tree-sitter-java)
add_ts_grammar(python     tree-sitter-python)
add_ts_grammar(javascript tree-sitter-javascript)
add_ts_grammar(typescript tree-sitter-typescript SUBDIR typescript)
add_ts_grammar(tsx        tree-sitter-typescript SUBDIR tsx)
add_ts_grammar(ruby       tree-sitter-ruby)
add_ts_grammar(bash       tree-sitter-bash)
add_ts_grammar(c_sharp    tree-sitter-c-sharp)
add_ts_grammar(html       tree-sitter-html)
add_ts_grammar(css        tree-sitter-css)
add_ts_grammar(lua        tree-sitter-lua)
add_ts_grammar(toml       tree-sitter-toml)
add_ts_grammar(cmake      tree-sitter-cmake
               LOCAL_QUERY ${CMAKE_CURRENT_SOURCE_DIR}/highlight/queries/cmake.scm)
add_ts_grammar(markdown   tree-sitter-markdown
               SUBDIR tree-sitter-markdown QUERY tree-sitter-markdown/queries/highlights.scm)
add_ts_grammar(json       tree-sitter-json)

# More languages can be added with an add_ts_grammar line here plus a matching
# registry entry in language.cc (extension, tree_sitter_<lang> binding, query
# chain). Use LOCAL_QUERY for grammars that ship no highlights.scm.

finalize_ts_queries(${CMAKE_CURRENT_BINARY_DIR}/ts_queries_generated.cc)
